### ISSUE TITLE
Error setting certificate verify locations

### ISSUE THREAD

**Issue by dwhoban** [mediabeastnz/craft-commerce-xero#1]
Thanks for making this plugin!  You released it just as I was about to start building.
 
I created `certs/privatekey.pem` in the root and got the following error on save. Look like it is looking in the root for `certificates/ca-bundle.crt` which is in the root of the plugin directory?

```
XeroPHP\Remote\Exception: Curl error: error setting certificate verify locations:
  CAfile: /home/vagrant/sites/allinseason.com.au/xero/certificates/ca-bundle.crt
  CApath: /etc/ssl/certs in /home/vagrant/sites/allinseason.com.au/vendor/calcinai/xero-php/src/XeroPHP/Remote/Request.php:123
Stack trace:
#0 /home/vagrant/sites/allinseason.com.au/vendor/calcinai/xero-php/src/XeroPHP/Remote/Query.php(287): XeroPHP\Remote\Request->send()
#1 /home/vagrant/sites/allinseason.com.au/vendor/calcinai/xero-php/src/XeroPHP/Remote/Query.php(304): XeroPHP\Remote\Query->execute()
#2 /home/vagrant/sites/allinseason.com.au/vendor/mediabeastnz/craft-commerce-xero/src/services/XeroConnectionService.php(163): XeroPHP\Remote\Query->first()
#3 [internal function]: mediabeastnz\xero\services\XeroConnectionService->mediabeastnz\xero\services\{closure}(Object(yii\redis\Cache))
#4 /home/vagrant/sites/allinseason.com.au/vendor/yiisoft/yii2/caching/Cache.php(597): call_user_func(Object(Closure), Object(yii\redis\Cache))
#5 /home/vagrant/sites/allinseason.com.au/vendor/mediabeastnz/craft-commerce-xero/src/services/XeroConnectionService.php(164): yii\caching\Cache->getOrSet('xero-organisati...', Object(Closure), 300)
#6 /home/vagrant/sites/allinseason.com.au/vendor/mediabeastnz/craft-commerce-xero/src/services/XeroConnectionService.php(70): mediabeastnz\xero\services\XeroConnectionService->getOrganisation(Object(XeroPHP\Application\PrivateApplication))
#7 /home/vagrant/sites/allinseason.com.au/vendor/mediabeastnz/craft-commerce-xero/src/Xero.php(155): mediabeastnz\xero\services\XeroConnectionService->setup()
#8 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/base/Plugin.php(224): mediabeastnz\xero\Xero->settingsHtml()
#9 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/controllers/PluginsController.php(119): craft\base\Plugin->getSettingsResponse()
#10 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('xero', Object(mediabeastnz\xero\Xero))
#11 /home/vagrant/sites/allinseason.com.au/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /home/vagrant/sites/allinseason.com.au/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('edit-plugin-set...', Array)
#14 /home/vagrant/sites/allinseason.com.au/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-plugin-set...', Array)
#15 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('plugins/edit-pl...', Array)
#16 /home/vagrant/sites/allinseason.com.au/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('plugins/edit-pl...', Array)
#17 /home/vagrant/sites/allinseason.com.au/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#18 /home/vagrant/sites/allinseason.com.au/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /home/vagrant/sites/allinseason.com.au/web/index.php(21): yii\base\Application->run()
#20 {main}
```

**Comment by mylesthedev** [comment]
Sorry @dwhoban I missed this one somehow. I'll update the plugin so it looks in the correct directory. Would you prefer to provide your own `ca-bundle.crt` do you think?

**Comment by dwhoban** [comment]
I think it's best to provide one as a default that could be over-ridden as a config

**Comment by mylesthedev** [comment]
@dwhoban i've just release `0.9.2` which now lets you define a path to a ca-bundle file. I've also updated the readme with a link to a good repo that contains a file you can download (generated from firefox's cert store).

Let me know how you get on.
