### ISSUE TITLE
Migration doesn't work on composer update

### ISSUE THREAD

**Issue by dwhoban** [mediabeastnz/craft-commerce-xero#9]
When I update the package via composer I cannot run the migration and get an invalid config error because the database tables required don't exist.

**Comment by dwhoban** [comment]
```
yii\base\InvalidConfigException: The table does not exist: {{%xero_connections}} in /app/vendor/yiisoft/yii2/db/ActiveRecord.php:438
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(469): yii\db\ActiveRecord::getTableSchema()
#1 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(500): yii\db\ActiveRecord->attributes()
#2 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(291): yii\db\BaseActiveRecord->hasAttribute('enabled')
#3 /app/plugins/craft-commerce-xero/src/services/XeroAPI.php(96): yii\db\BaseActiveRecord->__get('enabled')
#4 /app/plugins/craft-commerce-xero/src/Plugin.php(106): thejoshsmith\xero\services\XeroAPI->isConnected()
#5 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): thejoshsmith\xero\Plugin->init()
#6 /app/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#7 /app/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct('xero', Object(craft\web\Application), Array)
#8 [internal function]: craft\base\Plugin->__construct('xero', Object(craft\web\Application), Array)
#9 /app/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#10 /app/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('thejoshsmith\\xe...', Array, Array)
#11 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('thejoshsmith\\xe...', Array, Array)
#12 /app/vendor/craftcms/cms/src/services/Plugins.php(925): yii\BaseYii::createObject(Array, Array)
#13 /app/vendor/craftcms/cms/src/services/Plugins.php(228): craft\services\Plugins->createPlugin('xero', Array)
#14 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1431): craft\services\Plugins->loadPlugins()
#15 /app/vendor/craftcms/cms/src/web/Application.php(93): craft\web\Application->_postInit()
#16 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#17 /app/vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#18 [internal function]: yii\base\Application->__construct(Array)
#19 /app/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#20 /app/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#21 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#22 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array)
#23 /app/vendor/craftcms/cms/bootstrap/web.php(51): require('/app/vendor/cra...')
#24 /app/web/index.php(20): require('/app/vendor/cra...')
#25 {main}
```

**Comment by moacode** [comment]
Hey @dwhoban could you please try with v1.01 and raise an issue over at the [new repo](https://github.com/thejoshsmith/commerce-xero) if it's still not working for you? Thanks!

**Comment by dwhoban** [comment]
Ah, ok, didn't see the comment about the new plugin.

I think I will need to restore the old version and then uninstall and then reinstall the new one.

**Comment by moacode** [comment]
@dwhoban yeah it's a bit annoying. I talked to Brandon and he's going to transfer existing licenses for the old plugin to the new one so you won't need to re-purchase the new one.

If you export your `xero_invoices` db table before uninstalling/reinstalling and then import it again the plugin will remember your previously synced invoices.
